-- 24 entries — Thursday card takings booked to AFTER
-- Generated by docs/accounting-mess/propose-cost-centres.mjs — do not hand-edit.
-- Only ever fills an EMPTY cost centre, so it cannot overwrite a decision
-- already made in the app.
\set ON_ERROR_STOP on

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 240 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 265 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 266 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 304 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 335 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 372 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 392 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 408 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 409 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 410 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 425 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 426 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 427 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 436 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 437 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 438 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 449 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 455 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 456 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 457 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 548 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 593 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 601 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'AFTER'
  AND j."sequenceNumber" = 602 AND j."costCenterId" IS NULL;

SELECT cc.code, count(j.id) AS ecritures
FROM "CostCenter" cc
LEFT JOIN "JournalEntry" j ON j."costCenterId" = cc.id
WHERE cc."editionId" = (SELECT id FROM "Edition" WHERE name = '2025-2026')
GROUP BY cc.code ORDER BY cc.code;
