-- 143 entries — event windows, the festival, and general-meeting admin
-- Generated by docs/accounting-mess/propose-cost-centres.mjs — do not hand-edit.
-- Only ever fills an EMPTY cost centre, so it cannot overwrite a decision
-- already made in the app.
\set ON_ERROR_STOP on

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 225 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 226 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 227 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 228 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 230 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 232 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 233 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 234 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 310 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 311 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 312 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 314 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 315 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 316 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 317 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 320 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 321 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 322 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 323 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 324 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 325 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 326 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 327 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 328 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 329 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 341 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 342 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 343 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 344 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 345 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 346 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 347 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 348 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 349 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 350 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 351 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 352 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 353 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 487 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 488 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 490 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 491 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 492 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 493 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 494 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 495 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 496 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 497 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 498 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 499 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 500 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 501 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 502 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 503 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 504 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 507 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 508 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 509 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 512 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 513 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL3'
  AND j."sequenceNumber" = 604 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL3'
  AND j."sequenceNumber" = 605 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 400 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 435 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 454 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 458 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 459 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 460 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 461 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 462 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 465 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 466 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 467 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 468 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 469 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 477 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 478 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 479 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 480 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 481 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 482 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 483 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 484 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 485 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 486 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 489 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 505 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 506 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 514 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 515 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 516 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 517 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 521 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 522 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 523 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 524 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 525 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 526 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 527 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 528 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 529 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 530 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 531 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 540 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 541 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 542 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 543 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 544 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 545 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 546 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 547 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 549 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 550 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 551 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 552 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 553 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 554 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 555 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 556 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 557 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 558 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 559 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 560 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 561 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 562 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 563 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 565 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 566 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 567 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 568 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 569 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 570 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 571 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 572 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 577 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 578 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 579 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 582 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 583 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 584 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 585 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'INTERNE'
  AND j."sequenceNumber" = 298 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'INTERNE'
  AND j."sequenceNumber" = 319 AND j."costCenterId" IS NULL;

SELECT cc.code, count(j.id) AS ecritures
FROM "CostCenter" cc
LEFT JOIN "JournalEntry" j ON j."costCenterId" = cc.id
WHERE cc."editionId" = (SELECT id FROM "Edition" WHERE name = '2025-2026')
GROUP BY cc.code ORDER BY cc.code;
