-- Undoes apply.sql exactly: deletes the 50 rows it inserted, drops the
-- three cost centers it created, and puts the 2026-2027 cash carry-over back to
-- the value it held before (CHARGES 6554.03, written by the 24.08.2026 carry-over).
--
-- Generated by docs/accounting-mess/emit-production-sql.mjs — do not hand-edit.

\set ON_ERROR_STOP on

DELETE FROM "JournalEntry" WHERE id IN (
  'cd161284670da470112a1eef2',
  'c17ec7cb2d70f8dca410a11d4',
  'ca82764a90cfe3f5bc29eae51',
  'c131b431e462c09f0538d243d',
  'cb5ba762e615178d5c4fe9de4',
  'c643f12b306c51c5c7e503cbc',
  'c1da46987ac347f1e5a2907b1',
  'c02ca1b740a37ed2506fb211c',
  'c9c6b8f95f57f090a613fe7b8',
  'cf1f58555cb55d59209e2a26c',
  'c70793b9cd1eb3ee04d7dff44',
  'c7cbe319ad79cad47e1bf048a',
  'cd211bf4a2ca838ea41bd8aa9',
  'c73f05dcd924443d549edb168',
  'c3d17c5f05f57d681fc6b440a',
  'c30f2152a3246c9f5016a3671',
  'c5ed3fd8aaf6f61e1293d9703',
  'cc854136c2d2eddcabf8b3bab',
  'cfff612520fc0b377f6e9d4c9',
  'cd71f0874e2cdbd2e72fdf606',
  'c92c53e6a626c01def651a397',
  'ce7ff0606be47bbd4816f03bb',
  'ce1f7cf84b582f6c0582531e7',
  'cf71aacd065c72ec93c630366',
  'c638ca4b54eea7bcbace69425',
  'c35d266d6cf1e13cee3d55979',
  'c2452acee077895365dad657c',
  'c6a6c63a2a87ef242be7d433f',
  'c7640c3c74b0b3fa20200f322',
  'c452b2e945626c7d09c4c1e1f',
  'c5d5eeb098c31caae13d78475',
  'c4aace550a1036a18ad464fa3',
  'cc8f990c571526d2527714563',
  'c0b823a2cadecaccfe749017c',
  'c7f7c7d11db19c1e1c912fdfd',
  'c996d86f602df4db617825fde',
  'cdcb245461377f5d7095c0b0f',
  'cc55451afd22f1c37ec9f5483',
  'c98d9f23322a8e258baa2af95',
  'c4aad36a7c4c23decbde032f8',
  'c3749537c25ff86cdb9df0ce5',
  'cd60ead6f9ba9f6fcc0fe8aca',
  'cfd8e2b04dafa162f67f51f38',
  'c129a6fed8749fbdcbe7dc474',
  'cea7eae6402f41d974c1e1bd5',
  'c368b05a0b8c7091d4ff68cf9',
  'ca44fb77ef4ffb79af1714f82',
  'c056afff5113d56040dce804c',
  'c4a9e1bd6992dbc7e85a43289',
  'ca33bc04263cfb1666af31c74'
);

DELETE FROM "CostCenter" WHERE id IN (
  'cf3ba85e97ed6a38e85f216c5',
  'cd728718cb28f0d90408f66f5',
  'c76765c0de5c7930d9599f114',
  'ce11cc59bc65b6d09aa2119eb',
  'cb0ec90caa93f0c36acd392ca',
  'cb7e1212ea53f9a721c0a23bb'
);

UPDATE "JournalEntry" j
SET "accountType" = 'CHARGES'::"AccountType", amount = 6554.03, "updatedAt" = now()
FROM "MoneyAccount" ma, "Edition" ed
WHERE j."moneyAccountId" = ma.id
  AND ma."editionId" = ed.id
  AND ed.name = '2026-2027'
  AND ma.name = 'Coffre'
  AND j."isOpeningEntry" = true;
