-- Books the reconstituted 2025-2026 cash box and re-carries its balance.
--
-- Generated by docs/accounting-mess/emit-production-sql.mjs — do not hand-edit.
-- Run inside a single transaction:
--   psql -U blv -d baleinev_comptes -v ON_ERROR_STOP=1 --single-transaction -f apply.sql
--
-- Re-running is safe: every insert is ON CONFLICT DO NOTHING on a deterministic
-- id, and the carry-over UPDATE recomputes from the source edition each time.

\set ON_ERROR_STOP on

-- 1. The cost centers the reconstruction needs, in both editions so the new
--    year inherits the same chart the carry-over would have copied.
INSERT INTO "CostCenter" (id, "editionId", code, name, "createdAt", "updatedAt")
SELECT 'cf3ba85e97ed6a38e85f216c5', e.id, 'SVC', 'SVC', now(), now()
FROM "Edition" e WHERE e.name = '2025-2026'
ON CONFLICT ("editionId", code) DO NOTHING;

INSERT INTO "CostCenter" (id, "editionId", code, name, "createdAt", "updatedAt")
SELECT 'cd728718cb28f0d90408f66f5', e.id, 'SVC', 'SVC', now(), now()
FROM "Edition" e WHERE e.name = '2026-2027'
ON CONFLICT ("editionId", code) DO NOTHING;

INSERT INTO "CostCenter" (id, "editionId", code, name, "createdAt", "updatedAt")
SELECT 'c76765c0de5c7930d9599f114', e.id, 'SEGRILL2', 'SEGRILL2', now(), now()
FROM "Edition" e WHERE e.name = '2025-2026'
ON CONFLICT ("editionId", code) DO NOTHING;

INSERT INTO "CostCenter" (id, "editionId", code, name, "createdAt", "updatedAt")
SELECT 'ce11cc59bc65b6d09aa2119eb', e.id, 'SEGRILL2', 'SEGRILL2', now(), now()
FROM "Edition" e WHERE e.name = '2026-2027'
ON CONFLICT ("editionId", code) DO NOTHING;

INSERT INTO "CostCenter" (id, "editionId", code, name, "createdAt", "updatedAt")
SELECT 'cb0ec90caa93f0c36acd392ca', e.id, 'SEGRILL3', 'SEGRILL3', now(), now()
FROM "Edition" e WHERE e.name = '2025-2026'
ON CONFLICT ("editionId", code) DO NOTHING;

INSERT INTO "CostCenter" (id, "editionId", code, name, "createdAt", "updatedAt")
SELECT 'cb7e1212ea53f9a721c0a23bb', e.id, 'SEGRILL3', 'SEGRILL3', now(), now()
FROM "Edition" e WHERE e.name = '2026-2027'
ON CONFLICT ("editionId", code) DO NOTHING;

-- 2. The 50 reconstructed cash movements, sequences
--    615-664. Nothing existing is touched.
INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cd161284670da470112a1eef2', ma."editionId", ma.id, 'CHARGES'::"AccountType", 615,
       '2025-09-10'::timestamp, 400.00, 'BLV', 'Manque à gagner constaté au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c17ec7cb2d70f8dca410a11d4', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 616,
       '2025-10-31'::timestamp, 186.25, 'BLV', 'Équilibrage après comptage du coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'ca82764a90cfe3f5bc29eae51', ma."editionId", ma.id, 'CHARGES'::"AccountType", 617,
       '2025-11-29'::timestamp, 1390.00, 'BLV', 'MDN 29.11 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c131b431e462c09f0538d243d', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 618,
       '2025-11-29'::timestamp, 1954.00, 'BLV', 'MDN 29.11 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cb5ba762e615178d5c4fe9de4', ma."editionId", ma.id, 'CHARGES'::"AccountType", 619,
       '2025-11-30'::timestamp, 1114.00, 'BLV', 'MDN 30.11 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c643f12b306c51c5c7e503cbc', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 620,
       '2025-11-30'::timestamp, 1242.00, 'BLV', 'MDN 30.11 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c1da46987ac347f1e5a2907b1', ma."editionId", ma.id, 'CHARGES'::"AccountType", 621,
       '2025-11-30'::timestamp, 258.57, 'BLV', 'Équilibrage après comptage du coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c02ca1b740a37ed2506fb211c', ma."editionId", ma.id, 'CHARGES'::"AccountType", 622,
       '2025-12-01'::timestamp, 1002.00, 'BLV', 'MDN 01.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c9c6b8f95f57f090a613fe7b8', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 623,
       '2025-12-01'::timestamp, 1122.00, 'BLV', 'MDN 01.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cf1f58555cb55d59209e2a26c', ma."editionId", ma.id, 'CHARGES'::"AccountType", 624,
       '2025-12-02'::timestamp, 962.00, 'BLV', 'MDN 02.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c70793b9cd1eb3ee04d7dff44', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 625,
       '2025-12-02'::timestamp, 1033.60, 'BLV', 'MDN 02.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c7cbe319ad79cad47e1bf048a', ma."editionId", ma.id, 'CHARGES'::"AccountType", 626,
       '2025-12-03'::timestamp, 953.60, 'BLV', 'MDN 03.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cd211bf4a2ca838ea41bd8aa9', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 627,
       '2025-12-03'::timestamp, 942.80, 'BLV', 'MDN 03.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c73f05dcd924443d549edb168', ma."editionId", ma.id, 'CHARGES'::"AccountType", 628,
       '2025-12-04'::timestamp, 822.80, 'BLV', 'MDN 04.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c3d17c5f05f57d681fc6b440a', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 629,
       '2025-12-04'::timestamp, 882.80, 'BLV', 'MDN 04.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c30f2152a3246c9f5016a3671', ma."editionId", ma.id, 'CHARGES'::"AccountType", 630,
       '2025-12-05'::timestamp, 1002.80, 'BLV', 'MDN 05.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c5ed3fd8aaf6f61e1293d9703', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 631,
       '2025-12-05'::timestamp, 1660.35, 'BLV', 'MDN 05.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cc854136c2d2eddcabf8b3bab', ma."editionId", ma.id, 'CHARGES'::"AccountType", 632,
       '2025-12-06'::timestamp, 1042.35, 'BLV', 'MDN 06.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cfff612520fc0b377f6e9d4c9', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 633,
       '2025-12-06'::timestamp, 1356.75, 'BLV', 'MDN 06.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cd71f0874e2cdbd2e72fdf606', ma."editionId", ma.id, 'CHARGES'::"AccountType", 634,
       '2025-12-07'::timestamp, 956.75, 'BLV', 'MDN 07.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c92c53e6a626c01def651a397', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 635,
       '2025-12-07'::timestamp, 1037.80, 'BLV', 'MDN 07.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'MDN'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'ce7ff0606be47bbd4816f03bb', ma."editionId", ma.id, 'CHARGES'::"AccountType", 636,
       '2025-12-15'::timestamp, 192.50, 'BLV', 'SVC Chéseaux 15.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'ce1f7cf84b582f6c0582531e7', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 637,
       '2025-12-15'::timestamp, 289.50, 'BLV', 'SVC Chéseaux 15.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cf71aacd065c72ec93c630366', ma."editionId", ma.id, 'CHARGES'::"AccountType", 638,
       '2025-12-15'::timestamp, 190.00, 'BLV', 'SVC St-Roch 15.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c638ca4b54eea7bcbace69425', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 639,
       '2025-12-15'::timestamp, 254.00, 'BLV', 'SVC St-Roch 15.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c35d266d6cf1e13cee3d55979', ma."editionId", ma.id, 'CHARGES'::"AccountType", 640,
       '2025-12-16'::timestamp, 289.50, 'BLV', 'SVC Chéseaux 16.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c2452acee077895365dad657c', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 641,
       '2025-12-16'::timestamp, 443.50, 'BLV', 'SVC Chéseaux 16.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c6a6c63a2a87ef242be7d433f', ma."editionId", ma.id, 'CHARGES'::"AccountType", 642,
       '2025-12-16'::timestamp, 254.00, 'BLV', 'SVC St-Roch 16.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c7640c3c74b0b3fa20200f322', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 643,
       '2025-12-16'::timestamp, 306.00, 'BLV', 'SVC St-Roch 16.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c452b2e945626c7d09c4c1e1f', ma."editionId", ma.id, 'CHARGES'::"AccountType", 644,
       '2025-12-17'::timestamp, 443.50, 'BLV', 'SVC Chéseaux 17.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c5d5eeb098c31caae13d78475', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 645,
       '2025-12-17'::timestamp, 744.50, 'BLV', 'SVC Chéseaux 17.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c4aace550a1036a18ad464fa3', ma."editionId", ma.id, 'CHARGES'::"AccountType", 646,
       '2025-12-17'::timestamp, 306.00, 'BLV', 'SVC St-Roch 17.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cc8f990c571526d2527714563', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 647,
       '2025-12-17'::timestamp, 340.20, 'BLV', 'SVC St-Roch 17.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c0b823a2cadecaccfe749017c', ma."editionId", ma.id, 'CHARGES'::"AccountType", 648,
       '2025-12-18'::timestamp, 504.50, 'BLV', 'SVC Chéseaux 18.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c7f7c7d11db19c1e1c912fdfd', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 649,
       '2025-12-18'::timestamp, 1111.30, 'BLV', 'SVC Chéseaux 18.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c996d86f602df4db617825fde', ma."editionId", ma.id, 'CHARGES'::"AccountType", 650,
       '2025-12-18'::timestamp, 340.20, 'BLV', 'SVC St-Roch 18.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cdcb245461377f5d7095c0b0f', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 651,
       '2025-12-18'::timestamp, 393.60, 'BLV', 'SVC St-Roch 18.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cc55451afd22f1c37ec9f5483', ma."editionId", ma.id, 'CHARGES'::"AccountType", 652,
       '2025-12-19'::timestamp, 393.60, 'BLV', 'SVC St-Roch 19.12 : fonds de caisse sorti',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c98d9f23322a8e258baa2af95', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 653,
       '2025-12-19'::timestamp, 426.10, 'BLV', 'SVC St-Roch 19.12 : caisse comptée, rentrée au coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c4aad36a7c4c23decbde032f8', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 654,
       '2026-02-28'::timestamp, 348.65, 'BLV', 'Équilibrage après comptage du coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c3749537c25ff86cdb9df0ce5', ma."editionId", ma.id, 'CHARGES'::"AccountType", 655,
       '2026-03-31'::timestamp, 1.20, 'BLV', 'Équilibrage après comptage du coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cd60ead6f9ba9f6fcc0fe8aca', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 656,
       '2026-04-12'::timestamp, 141.65, 'BLV', 'Vidange crousille',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cfd8e2b04dafa162f67f51f38', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 657,
       '2026-04-12'::timestamp, 465.00, 'BLV', 'Vidange caisse St-Roch',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c129a6fed8749fbdcbe7dc474', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 658,
       '2026-04-12'::timestamp, 504.60, 'BLV', 'Vidange caisse Chéseaux',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SVC'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'cea7eae6402f41d974c1e1bd5', ma."editionId", ma.id, 'CHARGES'::"AccountType", 659,
       '2026-04-13'::timestamp, 495.00, 'BLV', 'Sortie du coffre vers la caisse',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SEGRILL2'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c368b05a0b8c7091d4ff68cf9', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 660,
       '2026-04-16'::timestamp, 1870.00, 'BLV', 'Entrées dans le coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SEGRILL2'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'ca44fb77ef4ffb79af1714f82', ma."editionId", ma.id, 'CHARGES'::"AccountType", 661,
       '2026-04-30'::timestamp, 468.90, 'BLV', 'Équilibrage après comptage du coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c056afff5113d56040dce804c', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 662,
       '2026-05-31'::timestamp, 1755.95, 'BLV', 'Équilibrage après comptage du coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'INTERNE'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'c4a9e1bd6992dbc7e85a43289', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 663,
       '2026-06-30'::timestamp, 382.20, 'BLV', 'Entrée dans le coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SEGRILL3'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

INSERT INTO "JournalEntry" (
  id, "editionId", "moneyAccountId", "accountType", "sequenceNumber", date, amount,
  counterparty, label, "costCenterId", "isOpeningEntry", "createdAt", "updatedAt")
SELECT 'ca33bc04263cfb1666af31c74', ma."editionId", ma.id, 'PRODUITS'::"AccountType", 664,
       '2026-06-30'::timestamp, 70.00, 'BLV', 'Entrée dans le coffre',
       (SELECT cc.id FROM "CostCenter" cc WHERE cc."editionId" = ma."editionId" AND cc.code = 'SEGRILL3'), false, now(), now()
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
ON CONFLICT (id) DO NOTHING;

-- 3. Re-carry the cash box into 2026-2027. The amount is recomputed from
--    the source edition rather than typed, so it cannot disagree with step 2.
--    The bank account's carry-over is already correct and is left alone.
WITH closing AS (
  SELECT ma."openingBalance" + COALESCE(SUM(
           CASE WHEN j."accountType" = 'PRODUITS' THEN j.amount ELSE -j.amount END
         ), 0) AS balance
  FROM "MoneyAccount" ma
  JOIN "Edition" ed ON ed.id = ma."editionId"
  LEFT JOIN "JournalEntry" j ON j."moneyAccountId" = ma.id
  WHERE ed.name = '2025-2026' AND ma.name = 'Coffre'
  GROUP BY ma.id, ma."openingBalance"
)
UPDATE "JournalEntry" j
SET "accountType" = CASE WHEN closing.balance >= 0 THEN 'PRODUITS' ELSE 'CHARGES' END::"AccountType",
    amount        = abs(closing.balance),
    "updatedAt"   = now()
FROM closing, "MoneyAccount" ma, "Edition" ed
WHERE j."moneyAccountId" = ma.id
  AND ma."editionId" = ed.id
  AND ed.name = '2026-2027'
  AND ma.name = 'Coffre'
  AND j."isOpeningEntry" = true;

-- 4. What the two editions look like afterwards.
SELECT ed.name AS edition, ma.name AS compte,
       ma."openingBalance" + COALESCE(SUM(
         CASE WHEN j."accountType" = 'PRODUITS' THEN j.amount ELSE -j.amount END
       ), 0) AS solde,
       count(j.id) AS ecritures
FROM "MoneyAccount" ma
JOIN "Edition" ed ON ed.id = ma."editionId"
LEFT JOIN "JournalEntry" j ON j."moneyAccountId" = ma.id
WHERE ed.name IN ('2025-2026', '2026-2027')
GROUP BY ed.name, ma.name, ma.id, ma."openingBalance"
ORDER BY ed.name, ma.name;
