-- Assigns a budget to 227 entries of the 2025-2026 journal.
-- Generated by docs/accounting-mess/assign-budgets.mjs — do not hand-edit.
-- Only ever fills an EMPTY budget, so it cannot overwrite a decision already
-- made in the app.
\set ON_ERROR_STOP on

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 615 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 225 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 226 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 227 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 228 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 230 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 231 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 232 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 233 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 234 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 240 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 255 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 265 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 266 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 616 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 272 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 275 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 298 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 304 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 617 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 618 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 619 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 620 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 621 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 310 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 311 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 312 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 313 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 622 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 623 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 314 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 315 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 316 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 317 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 319 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 320 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 624 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 625 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 321 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 322 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 323 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 626 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 627 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 324 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 628 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 629 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 325 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 326 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 327 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 630 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 631 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 632 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 633 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 328 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 329 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 634 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 635 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 335 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 341 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 636 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 637 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 638 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 639 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 640 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 641 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 642 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 643 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 342 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 343 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 344 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 345 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 644 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 645 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 646 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 647 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 346 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 347 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 348 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 349 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 350 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 648 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 649 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 650 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 651 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 351 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 352 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 353 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 652 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 653 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 372 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 392 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 400 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 654 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'COMMUNICATION'
  AND j."sequenceNumber" = 403 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 408 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 409 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 410 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 425 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 426 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 427 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 435 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 436 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 437 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 438 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'COMMUNICATION'
  AND j."sequenceNumber" = 441 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 449 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 655 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 454 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 455 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 456 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 457 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 458 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 459 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 460 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 461 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 462 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 465 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 466 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 467 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 468 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 469 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 477 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 478 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 479 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 480 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 481 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 482 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 483 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 484 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 485 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 486 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 656 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 657 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 658 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 487 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 488 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 489 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 659 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 490 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 491 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 492 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 493 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 494 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 495 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 496 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 497 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 498 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 499 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 500 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 501 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 502 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 503 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 504 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 505 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 506 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 660 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 507 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 508 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 509 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 512 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 513 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 514 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 515 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 516 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 517 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 521 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 522 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 523 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 524 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 525 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 526 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 527 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 528 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 529 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 530 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 531 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 540 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 541 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 542 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 543 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 544 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 545 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 546 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 547 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 548 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 661 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 549 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 550 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 551 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 552 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 553 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 554 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 555 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 556 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 557 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 558 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 559 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 560 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 561 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 562 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 563 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 565 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 566 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 567 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 568 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 569 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 570 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'COMMUNICATION'
  AND j."sequenceNumber" = 571 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 572 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 577 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 578 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 579 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 582 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 583 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 584 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 585 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 662 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 593 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 601 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 602 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 604 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 605 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 663 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'EVENTS'
  AND j."sequenceNumber" = 664 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'TECHNIQUE'
  AND j."sequenceNumber" = 607 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'TECHNIQUE'
  AND j."sequenceNumber" = 608 AND j."budgetId" IS NULL;

UPDATE "JournalEntry" j SET "budgetId" = b.id, "updatedAt" = now()
FROM "Budget" b, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND b."editionId" = ed.id AND b.name = 'ADMINISTRATION'
  AND j."sequenceNumber" = 614 AND j."budgetId" IS NULL;

SELECT b.name, count(j.id) AS ecritures,
       to_char(sum(CASE WHEN j."accountType" = 'PRODUITS' THEN j.amount ELSE -j.amount END), 'FM999G999D00') AS net
FROM "Budget" b
JOIN "JournalEntry" j ON j."budgetId" = b.id
WHERE b."editionId" = (SELECT id FROM "Edition" WHERE name = '2025-2026')
GROUP BY b.name ORDER BY b.name;
