-- 65 entries — event windows and April ticket sales
-- Generated by docs/accounting-mess/propose-cost-centres.mjs — do not hand-edit.
-- Only ever fills an EMPTY cost centre, so it cannot overwrite a decision
-- already made in the app.
\set ON_ERROR_STOP on

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 225 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 226 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 227 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 228 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 230 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 232 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 233 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL1'
  AND j."sequenceNumber" = 234 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 310 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 311 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 312 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 314 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 315 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 316 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 317 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 320 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 321 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 322 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 323 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 324 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 325 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 326 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 327 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 328 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'MDN'
  AND j."sequenceNumber" = 329 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 341 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 342 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 343 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 344 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 345 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 346 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 347 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 348 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 349 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 350 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 351 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 352 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SVC'
  AND j."sequenceNumber" = 353 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 487 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 488 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 490 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 491 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 492 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 493 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 494 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 495 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 496 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 497 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 498 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 499 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 500 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 501 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 502 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 503 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 504 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 507 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 508 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 509 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 512 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL2'
  AND j."sequenceNumber" = 513 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL3'
  AND j."sequenceNumber" = 604 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'SEGRILL3'
  AND j."sequenceNumber" = 605 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 466 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 521 AND j."costCenterId" IS NULL;

UPDATE "JournalEntry" j SET "costCenterId" = cc.id, "updatedAt" = now()
FROM "CostCenter" cc, "Edition" ed
WHERE ed.name = '2025-2026' AND j."editionId" = ed.id
  AND cc."editionId" = ed.id AND cc.code = 'FESTIVAL'
  AND j."sequenceNumber" = 544 AND j."costCenterId" IS NULL;

SELECT cc.code, count(j.id) AS ecritures
FROM "CostCenter" cc
LEFT JOIN "JournalEntry" j ON j."costCenterId" = cc.id
WHERE cc."editionId" = (SELECT id FROM "Edition" WHERE name = '2025-2026')
GROUP BY cc.code ORDER BY cc.code;
